from . import groupe
from . import universite
from . import departement
from . import enseignant
from . import filiere
from . import module
from . import martiere
from . import salle
from . import epreuve
from . import seance
from . import absence
from . import etudiant
from . import annee
from . import epreuve_etudiant
from . import  note
from . import  epet
from . import absence2